from __future__ import annotations

from sqlalchemy import Engine, text

from shared.migrations import run_sql_migrations, table_columns


def _timestamp_type(engine: Engine) -> str:
    return "TIMESTAMP" if engine.dialect.name == "postgresql" else "DATETIME"


def _id_column_type(engine: Engine) -> str:
    if engine.dialect.name == "postgresql":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER NOT NULL PRIMARY KEY"


def _base_migrations(engine: Engine) -> list[tuple[str, str]]:
    timestamp = _timestamp_type(engine)
    return [
        (
            "20260615_0001_agent_async_tasks",
            f"""
            CREATE TABLE IF NOT EXISTS agent_async_tasks (
                id {_id_column_type(engine)},
                request_id VARCHAR(160) NOT NULL UNIQUE,
                task_type VARCHAR(60) NOT NULL,
                status VARCHAR(24) NOT NULL DEFAULT 'pending',
                payload_json TEXT NOT NULL,
                callback_context_json TEXT NOT NULL DEFAULT '{{}}',
                attempts INTEGER NOT NULL DEFAULT 0,
                max_attempts INTEGER NOT NULL DEFAULT 3,
                last_error TEXT NOT NULL DEFAULT '',
                accepted_at {timestamp},
                run_after {timestamp},
                started_at {timestamp},
                locked_by VARCHAR(160) NOT NULL DEFAULT '',
                locked_until {timestamp},
                completed_at {timestamp}
            )
            """,
        ),
        (
            "20260617_0002_agent_worker_heartbeats",
            f"""
            CREATE TABLE IF NOT EXISTS agent_worker_heartbeats (
                id {_id_column_type(engine)},
                worker_id VARCHAR(200) NOT NULL UNIQUE,
                status VARCHAR(24) NOT NULL DEFAULT 'running',
                started_at {timestamp},
                heartbeat_at {timestamp},
                stopped_at {timestamp},
                current_task_request_id VARCHAR(160) NOT NULL DEFAULT '',
                current_task_type VARCHAR(60) NOT NULL DEFAULT '',
                processed_count INTEGER NOT NULL DEFAULT 0,
                last_error TEXT NOT NULL DEFAULT ''
            )
            """,
        ),
    ]


def ensure_agent_async_task_columns(engine: Engine) -> None:
    timestamp = _timestamp_type(engine)
    columns: dict[str, str] = {
        "max_attempts": "INTEGER NOT NULL DEFAULT 3",
        "run_after": timestamp,
        "locked_by": "VARCHAR(160) NOT NULL DEFAULT ''",
        "locked_until": timestamp,
    }
    with engine.begin() as connection:
        existing_columns = table_columns(connection, "agent_async_tasks")
        if not existing_columns:
            return
        for column_name, column_type in columns.items():
            if column_name in existing_columns:
                continue
            connection.execute(text(f"ALTER TABLE agent_async_tasks ADD COLUMN {column_name} {column_type}"))


def ensure_agent_worker_heartbeat_columns(engine: Engine) -> None:
    timestamp = _timestamp_type(engine)
    columns: dict[str, str] = {
        "stopped_at": timestamp,
        "current_task_request_id": "VARCHAR(160) NOT NULL DEFAULT ''",
        "current_task_type": "VARCHAR(60) NOT NULL DEFAULT ''",
        "processed_count": "INTEGER NOT NULL DEFAULT 0",
        "last_error": "TEXT NOT NULL DEFAULT ''",
    }
    with engine.begin() as connection:
        existing_columns = table_columns(connection, "agent_worker_heartbeats")
        if not existing_columns:
            return
        for column_name, column_type in columns.items():
            if column_name in existing_columns:
                continue
            connection.execute(text(f"ALTER TABLE agent_worker_heartbeats ADD COLUMN {column_name} {column_type}"))


def run_migrations(engine: Engine) -> list[str]:
    applied = run_sql_migrations(engine, _base_migrations(engine))
    ensure_agent_async_task_columns(engine)
    ensure_agent_worker_heartbeat_columns(engine)
    return applied
