from __future__ import annotations

from sqlalchemy import Engine, text

from shared.migrations import run_sql_migrations, table_columns


def _timestamp_type(engine: Engine) -> str:
    _require_postgresql(engine)
    return "TIMESTAMP"


def _id_column_type(engine: Engine) -> str:
    _require_postgresql(engine)
    return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def _require_postgresql(engine: Engine) -> None:
    if engine.dialect.name != "postgresql":
        raise RuntimeError(
            f"agent_migration_postgresql_required:{engine.dialect.name}"
        )


def _base_migrations(engine: Engine) -> list[tuple[str, str]]:
    timestamp = _timestamp_type(engine)
    return [
        (
            "20260615_0001_agent_async_tasks",
            f"""
            CREATE TABLE IF NOT EXISTS agent_async_tasks (
                id {_id_column_type(engine)},
                request_id VARCHAR(160) NOT NULL UNIQUE,
                deduplication_key VARCHAR(255),
                task_type VARCHAR(60) NOT NULL,
                status VARCHAR(24) NOT NULL DEFAULT 'pending',
                payload_json TEXT NOT NULL,
                callback_context_json TEXT NOT NULL DEFAULT '{{}}',
                attempts INTEGER NOT NULL DEFAULT 0,
                max_attempts INTEGER NOT NULL DEFAULT 3,
                last_error TEXT NOT NULL DEFAULT '',
                accepted_at {timestamp},
                run_after {timestamp},
                started_at {timestamp},
                locked_by VARCHAR(160) NOT NULL DEFAULT '',
                locked_until {timestamp},
                completed_at {timestamp}
            )
            """,
        ),
        (
            "20260617_0002_agent_worker_heartbeats",
            f"""
            CREATE TABLE IF NOT EXISTS agent_worker_heartbeats (
                id {_id_column_type(engine)},
                worker_id VARCHAR(200) NOT NULL UNIQUE,
                status VARCHAR(24) NOT NULL DEFAULT 'running',
                started_at {timestamp},
                heartbeat_at {timestamp},
                stopped_at {timestamp},
                current_task_request_id VARCHAR(160) NOT NULL DEFAULT '',
                current_task_type VARCHAR(60) NOT NULL DEFAULT '',
                processed_count INTEGER NOT NULL DEFAULT 0,
                last_error TEXT NOT NULL DEFAULT ''
            )
            """,
        ),
        (
            "20260725_0003_agent_sync_requests",
            f"""
            CREATE TABLE IF NOT EXISTS agent_sync_requests (
                id {_id_column_type(engine)},
                api_path VARCHAR(160) NOT NULL,
                request_id VARCHAR(160) NOT NULL,
                request_hash VARCHAR(64) NOT NULL,
                patient_id VARCHAR(160) NOT NULL,
                message_id VARCHAR(160) NOT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
                attempt_epoch INTEGER NOT NULL DEFAULT 0,
                trace_id VARCHAR(160) NOT NULL DEFAULT '',
                response_status INTEGER,
                response_json TEXT NOT NULL DEFAULT '',
                last_error_code VARCHAR(80) NOT NULL DEFAULT '',
                created_at {timestamp},
                updated_at {timestamp},
                processing_started_at {timestamp},
                lease_expires_at {timestamp},
                completed_at {timestamp},
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_sync_requests_path_request UNIQUE (api_path, request_id)
            )
            """,
        ),
        (
            "20260725_0004_agent_patient_locks",
            f"""
            CREATE TABLE IF NOT EXISTS agent_patient_locks (
                id {_id_column_type(engine)},
                patient_id VARCHAR(160) NOT NULL UNIQUE,
                request_id VARCHAR(160) NOT NULL,
                attempt_epoch INTEGER NOT NULL DEFAULT 0,
                lease_expires_at {timestamp} NOT NULL,
                created_at {timestamp},
                updated_at {timestamp}
            )
            """,
        ),
        (
            "20260725_0005_agent_sync_request_lookup_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_sync_requests_patient_status
            ON agent_sync_requests (patient_id, status)
            """,
        ),
        (
            "20260725_0006_agent_sync_request_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_sync_requests_expires_at
            ON agent_sync_requests (expires_at)
            """,
        ),
        (
            "20260725_0007_agent_run_traces",
            f"""
            CREATE TABLE IF NOT EXISTS agent_run_traces (
                id {_id_column_type(engine)},
                trace_id VARCHAR(160) NOT NULL UNIQUE,
                request_id VARCHAR(160) NOT NULL,
                api_path VARCHAR(160) NOT NULL DEFAULT '',
                message_id VARCHAR(160) NOT NULL DEFAULT '',
                patient_id_hash VARCHAR(64) NOT NULL DEFAULT '',
                environment VARCHAR(40) NOT NULL DEFAULT '',
                release_version VARCHAR(120) NOT NULL DEFAULT '',
                workflow_name VARCHAR(120) NOT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'PROCESSING',
                agent_name VARCHAR(120) NOT NULL DEFAULT '',
                decision_type VARCHAR(80) NOT NULL DEFAULT '',
                route VARCHAR(120) NOT NULL DEFAULT '',
                fallback_reason VARCHAR(160) NOT NULL DEFAULT '',
                prompt_version_id VARCHAR(120) NOT NULL DEFAULT '',
                provider VARCHAR(80) NOT NULL DEFAULT '',
                model_tier VARCHAR(40) NOT NULL DEFAULT '',
                model_id VARCHAR(255) NOT NULL DEFAULT '',
                input_hash VARCHAR(64) NOT NULL DEFAULT '',
                output_hash VARCHAR(64) NOT NULL DEFAULT '',
                input_tokens INTEGER NOT NULL DEFAULT 0,
                output_tokens INTEGER NOT NULL DEFAULT 0,
                estimated_cost_usd FLOAT NOT NULL DEFAULT 0,
                latency_ms INTEGER NOT NULL DEFAULT 0,
                tool_count INTEGER NOT NULL DEFAULT 0,
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                error_message TEXT NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{{}}',
                started_at TEXT NOT NULL,
                completed_at TEXT,
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL
            )
            """,
        ),
        (
            "20260725_0008_agent_run_traces_request_status_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_run_traces_request_status
            ON agent_run_traces (request_id, status)
            """,
        ),
        (
            "20260725_0009_agent_run_traces_patient_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_run_traces_patient_created
            ON agent_run_traces (patient_id_hash, created_at)
            """,
        ),
        (
            "20260725_0010_agent_run_steps",
            f"""
            CREATE TABLE IF NOT EXISTS agent_run_steps (
                id {_id_column_type(engine)},
                trace_id VARCHAR(160) NOT NULL,
                sequence INTEGER NOT NULL,
                step_type VARCHAR(60) NOT NULL,
                step_name VARCHAR(120) NOT NULL DEFAULT '',
                status VARCHAR(32) NOT NULL DEFAULT '',
                tool_name VARCHAR(160) NOT NULL DEFAULT '',
                tool_version VARCHAR(80) NOT NULL DEFAULT '',
                argument_schema_version VARCHAR(80) NOT NULL DEFAULT '',
                argument_hash VARCHAR(64) NOT NULL DEFAULT '',
                side_effect_level VARCHAR(40) NOT NULL DEFAULT '',
                retry_count INTEGER NOT NULL DEFAULT 0,
                latency_ms INTEGER NOT NULL DEFAULT 0,
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{{}}',
                started_at {timestamp},
                completed_at {timestamp},
                created_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_run_steps_trace_sequence UNIQUE (trace_id, sequence),
                FOREIGN KEY(trace_id) REFERENCES agent_run_traces (trace_id) ON DELETE CASCADE
            )
            """,
        ),
        (
            "20260725_0011_agent_tool_executions",
            f"""
            CREATE TABLE IF NOT EXISTS agent_tool_executions (
                id {_id_column_type(engine)},
                trace_id VARCHAR(160) NOT NULL,
                request_id VARCHAR(160) NOT NULL,
                patient_id_hash VARCHAR(64) NOT NULL,
                tool_call_id VARCHAR(180) NOT NULL,
                tool_name VARCHAR(160) NOT NULL,
                tool_version VARCHAR(80) NOT NULL DEFAULT '',
                argument_schema_version VARCHAR(80) NOT NULL DEFAULT '',
                argument_hash VARCHAR(64) NOT NULL DEFAULT '',
                status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
                side_effect_level VARCHAR(40) NOT NULL DEFAULT '',
                attempt_count INTEGER NOT NULL DEFAULT 0,
                response_hash VARCHAR(64) NOT NULL DEFAULT '',
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                retryable BOOLEAN NOT NULL DEFAULT FALSE,
                metadata_json TEXT NOT NULL DEFAULT '{{}}',
                started_at {timestamp},
                completed_at {timestamp},
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_tool_executions_trace_call UNIQUE (trace_id, tool_call_id)
            )
            """,
        ),
        (
            "20260725_0012_agent_tool_executions_request_status_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_tool_executions_request_status
            ON agent_tool_executions (request_id, status)
            """,
        ),
        (
            "20260725_0013_agent_pending_actions",
            f"""
            CREATE TABLE IF NOT EXISTS agent_pending_actions (
                id {_id_column_type(engine)},
                public_id VARCHAR(80) NOT NULL UNIQUE,
                source_chat_request_id VARCHAR(160) NOT NULL,
                source_message_id VARCHAR(160) NOT NULL,
                trace_id VARCHAR(160) NOT NULL,
                patient_id_hash VARCHAR(64) NOT NULL,
                action_type VARCHAR(60) NOT NULL,
                action_name VARCHAR(160) NOT NULL,
                tool_call_id VARCHAR(180) NOT NULL DEFAULT '',
                action_fingerprint VARCHAR(64) NOT NULL,
                target_resource_type VARCHAR(80) NOT NULL DEFAULT '',
                target_record_id VARCHAR(160) NOT NULL DEFAULT '',
                expected_version INTEGER,
                display_json TEXT NOT NULL DEFAULT '{{}}',
                payload_ciphertext TEXT NOT NULL DEFAULT '',
                payload_hash VARCHAR(64) NOT NULL DEFAULT '',
                encryption_key_id VARCHAR(120) NOT NULL DEFAULT '',
                status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
                confirmation_message_id VARCHAR(160) NOT NULL DEFAULT '',
                result_ciphertext TEXT NOT NULL DEFAULT '',
                result_hash VARCHAR(64) NOT NULL DEFAULT '',
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                execution_started_at {timestamp},
                resolved_at {timestamp},
                action_expires_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL
            )
            """,
        ),
        (
            "20260725_0014_agent_pending_actions_active_index",
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_pending_actions_active_patient
            ON agent_pending_actions (patient_id_hash)
            WHERE status IN ('PENDING', 'EXECUTING')
            """,
        ),
        (
            "20260725_0015_agent_feedback_links",
            f"""
            CREATE TABLE IF NOT EXISTS agent_feedback_links (
                id {_id_column_type(engine)},
                api_path VARCHAR(160) NOT NULL,
                request_id VARCHAR(160) NOT NULL,
                request_hash VARCHAR(64) NOT NULL DEFAULT '',
                message_id VARCHAR(160) NOT NULL,
                patient_id_hash VARCHAR(64) NOT NULL,
                trace_id VARCHAR(160) NOT NULL DEFAULT '',
                feedback BOOLEAN,
                feedback_text_ciphertext TEXT NOT NULL DEFAULT '',
                feedback_text_hash VARCHAR(64) NOT NULL DEFAULT '',
                encryption_key_id VARCHAR(120) NOT NULL DEFAULT '',
                status VARCHAR(32) NOT NULL DEFAULT 'ACCEPTED',
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                response_status INTEGER NOT NULL DEFAULT 202,
                response_json TEXT NOT NULL DEFAULT '{{"status":"accepted"}}',
                attempt_count INTEGER NOT NULL DEFAULT 0,
                max_attempts INTEGER NOT NULL DEFAULT 3,
                feedback_at {timestamp} NOT NULL,
                next_attempt_at {timestamp},
                last_attempt_at {timestamp},
                processed_at {timestamp},
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_feedback_links_path_request UNIQUE (api_path, request_id)
            )
            """,
        ),
        (
            "20260725_0016_agent_feedback_links_message_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_feedback_links_message_patient
            ON agent_feedback_links (message_id, patient_id_hash)
            """,
        ),
        (
            "20260725_0017_agent_state_expiry_indexes",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_pending_actions_expires_at
            ON agent_pending_actions (expires_at)
            """,
        ),
        (
            "20260725_0018_agent_trace_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_run_traces_expires_at
            ON agent_run_traces (expires_at)
            """,
        ),
        (
            "20260725_0019_agent_tool_execution_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_tool_executions_expires_at
            ON agent_tool_executions (expires_at)
            """,
        ),
        (
            "20260725_0020_agent_feedback_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_feedback_links_expires_at
            ON agent_feedback_links (expires_at)
            """,
        ),
        (
            "20260725_0021_agent_backend_write_requests",
            f"""
            CREATE TABLE IF NOT EXISTS agent_backend_write_requests (
                id {_id_column_type(engine)},
                request_id VARCHAR(160) NOT NULL,
                source_chat_request_id VARCHAR(160) NOT NULL,
                patient_id_hash VARCHAR(64) NOT NULL DEFAULT '',
                trusted_context_hash VARCHAR(64) NOT NULL,
                tool_call_id VARCHAR(180) NOT NULL,
                tool_name VARCHAR(160) NOT NULL,
                argument_hash VARCHAR(64) NOT NULL,
                expected_version INTEGER,
                status VARCHAR(32) NOT NULL DEFAULT 'PREPARED',
                attempt_count INTEGER NOT NULL DEFAULT 0,
                response_status INTEGER,
                response_json TEXT NOT NULL DEFAULT '',
                response_hash VARCHAR(64) NOT NULL DEFAULT '',
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                last_attempt_at {timestamp},
                completed_at {timestamp},
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_backend_write_requests_request UNIQUE (request_id),
                CONSTRAINT uq_agent_backend_write_requests_logical_call
                UNIQUE (
                    source_chat_request_id,
                    tool_name,
                    argument_hash,
                    trusted_context_hash
                )
            )
            """,
        ),
        (
            "20260725_0022_agent_backend_write_request_indexes",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_backend_write_requests_source_status
            ON agent_backend_write_requests (source_chat_request_id, status)
            """,
        ),
        (
            "20260725_0023_agent_backend_write_request_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_backend_write_requests_expires_at
            ON agent_backend_write_requests (expires_at)
            """,
        ),
        (
            "20260725_0024_agent_backend_write_logical_call_index",
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_backend_write_requests_logical_call
            ON agent_backend_write_requests (
                source_chat_request_id,
                tool_name,
                argument_hash,
                trusted_context_hash
            )
            """,
        ),
        (
            "20260727_0029_agent_async_task_claim_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_async_tasks_claim
            ON agent_async_tasks (
                status,
                run_after,
                accepted_at,
                id
            )
            """,
        ),
        (
            "20260728_0030_daily_pattern_task_deduplication",
            """
            ALTER TABLE agent_async_tasks
            ADD COLUMN IF NOT EXISTS deduplication_key VARCHAR(255);

            CREATE UNIQUE INDEX IF NOT EXISTS
                uq_agent_async_tasks_deduplication_key
            ON agent_async_tasks (deduplication_key)
            WHERE deduplication_key IS NOT NULL
            """,
        ),
        (
            "20260729_0033_agent_internal_approval_binding",
            """
            ALTER TABLE agent_pending_actions
                ADD COLUMN IF NOT EXISTS approved_source_chat_request_id
                    VARCHAR(160) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS write_request_id
                    VARCHAR(160) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS request_body_hash
                    VARCHAR(64) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS send_attempt_count
                    INTEGER NOT NULL DEFAULT 0;
            CREATE UNIQUE INDEX IF NOT EXISTS
                uq_agent_pending_actions_active_patient
            ON agent_pending_actions (patient_id_hash)
            WHERE status IN ('PENDING', 'APPROVED', 'SENDING');
            CREATE INDEX IF NOT EXISTS
                ix_agent_pending_actions_write_request_id
            ON agent_pending_actions (write_request_id)
            """,
        ),
        (
            "20260729_0034_agent_observation_ledger",
            f"""
            ALTER TABLE agent_async_tasks
                ADD COLUMN IF NOT EXISTS expires_at {timestamp};
            UPDATE agent_async_tasks
            SET expires_at = COALESCE(
                expires_at,
                accepted_at + INTERVAL '30 days',
                CURRENT_TIMESTAMP + INTERVAL '30 days'
            );
            ALTER TABLE agent_async_tasks
                ALTER COLUMN expires_at SET NOT NULL;
            CREATE INDEX IF NOT EXISTS
                ix_agent_async_tasks_expires_at
            ON agent_async_tasks (expires_at);

            ALTER TABLE agent_run_traces
                ADD COLUMN IF NOT EXISTS final_answer_source
                    VARCHAR(160) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS attempt_count
                    INTEGER NOT NULL DEFAULT 0;
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = current_schema()
                      AND table_name = 'agent_run_traces'
                      AND column_name = 'fallback_reason'
                ) THEN
                    UPDATE agent_run_traces
                    SET final_answer_source = fallback_reason
                    WHERE final_answer_source = ''
                      AND fallback_reason <> '';
                END IF;
            END
            $$;
            UPDATE agent_run_traces
            SET attempt_count = 1
            WHERE attempt_count = 0;

            ALTER TABLE agent_run_steps
                ADD COLUMN IF NOT EXISTS observation_id
                    VARCHAR(64) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS parent_observation_id
                    VARCHAR(64) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS observation_type
                    VARCHAR(40) NOT NULL DEFAULT 'span',
                ADD COLUMN IF NOT EXISTS trace_attempt_number
                    INTEGER NOT NULL DEFAULT 1,
                ADD COLUMN IF NOT EXISTS time_to_first_token_ms
                    INTEGER NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS level
                    VARCHAR(20) NOT NULL DEFAULT 'DEFAULT',
                ADD COLUMN IF NOT EXISTS status_message
                    TEXT NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS prompt_version_id
                    VARCHAR(120) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS provider
                    VARCHAR(80) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS model_id
                    VARCHAR(255) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS input_hash
                    VARCHAR(64) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS output_hash
                    VARCHAR(64) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS input_tokens
                    INTEGER NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS output_tokens
                    INTEGER NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS estimated_cost_usd
                    FLOAT NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS model_parameters_json
                    TEXT NOT NULL DEFAULT '{{}}',
                ADD COLUMN IF NOT EXISTS usage_details_json
                    TEXT NOT NULL DEFAULT '{{}}',
                ADD COLUMN IF NOT EXISTS cost_details_json
                    TEXT NOT NULL DEFAULT '{{}}',
                ADD COLUMN IF NOT EXISTS completion_start_time
                    {timestamp};
            UPDATE agent_run_steps
            SET observation_id = md5(trace_id || ':' || sequence::text),
                observation_type = CASE step_type
                    WHEN 'request_ingress' THEN 'agent'
                    WHEN 'model_call' THEN 'generation'
                    WHEN 'tool_call' THEN 'tool'
                    ELSE 'span'
                END
            WHERE observation_id = ''
               OR observation_type = 'span';
            CREATE INDEX IF NOT EXISTS
                ix_agent_run_steps_observation_id
            ON agent_run_steps (observation_id);

            ALTER TABLE agent_tool_executions
                ADD COLUMN IF NOT EXISTS trace_attempt_number
                    INTEGER NOT NULL DEFAULT 1,
                ADD COLUMN IF NOT EXISTS latency_ms
                    INTEGER NOT NULL DEFAULT 0;
            ALTER TABLE agent_tool_executions
                DROP CONSTRAINT IF EXISTS
                    uq_agent_tool_executions_trace_call;
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'uq_agent_tool_executions_trace_attempt_call'
                      AND conrelid =
                        'agent_tool_executions'::regclass
                ) THEN
                    ALTER TABLE agent_tool_executions
                        ADD CONSTRAINT
                            uq_agent_tool_executions_trace_attempt_call
                        UNIQUE (
                            trace_id,
                            trace_attempt_number,
                            tool_call_id
                        );
                END IF;
            END
            $$;
            """,
        ),
        (
            "20260729_0035_agent_observability_outbox",
            f"""
            CREATE TABLE IF NOT EXISTS agent_observability_exports (
                id SERIAL PRIMARY KEY,
                destination VARCHAR(40) NOT NULL DEFAULT 'langfuse',
                event_key VARCHAR(255) NOT NULL,
                event_type VARCHAR(40) NOT NULL,
                trace_id VARCHAR(160) NOT NULL,
                trace_attempt_number INTEGER NOT NULL DEFAULT 0,
                payload_json TEXT NOT NULL DEFAULT '{{}}',
                status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
                attempt_count INTEGER NOT NULL DEFAULT 0,
                max_attempts INTEGER NOT NULL DEFAULT 12,
                next_attempt_at {timestamp},
                locked_by VARCHAR(160) NOT NULL DEFAULT '',
                lease_expires_at {timestamp},
                last_error_code VARCHAR(80) NOT NULL DEFAULT '',
                last_error_message TEXT NOT NULL DEFAULT '',
                remote_trace_id VARCHAR(64) NOT NULL DEFAULT '',
                created_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                exported_at {timestamp},
                expires_at {timestamp} NOT NULL,
                CONSTRAINT
                    uq_agent_observability_exports_destination_event
                UNIQUE (destination, event_key)
            );
            CREATE INDEX IF NOT EXISTS
                ix_agent_observability_exports_event_type
            ON agent_observability_exports (event_type);
            CREATE INDEX IF NOT EXISTS
                ix_agent_observability_exports_trace_id
            ON agent_observability_exports (trace_id);
            CREATE INDEX IF NOT EXISTS
                ix_agent_observability_exports_status
            ON agent_observability_exports (status);
            CREATE INDEX IF NOT EXISTS
                ix_agent_observability_exports_next_attempt_at
            ON agent_observability_exports (next_attempt_at);
            CREATE INDEX IF NOT EXISTS
                ix_agent_observability_exports_lease_expires_at
            ON agent_observability_exports (lease_expires_at);
            CREATE INDEX IF NOT EXISTS
                ix_agent_observability_exports_expires_at
            ON agent_observability_exports (expires_at);
            CREATE INDEX IF NOT EXISTS
                ix_agent_observability_exports_due
            ON agent_observability_exports (
                destination,
                status,
                next_attempt_at,
                id
            );
            """,
        ),
        (
            "20260729_0036_remove_conversation_named_objects",
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_class
                    WHERE relkind = 'i'
                      AND relname =
                          'ix_agent_tool_executions_conversation_id'
                ) AND NOT EXISTS (
                    SELECT 1
                    FROM pg_class
                    WHERE relkind = 'i'
                      AND relname =
                          'ix_agent_tool_executions_patient_id_hash'
                ) THEN
                    ALTER INDEX
                        ix_agent_tool_executions_conversation_id
                    RENAME TO
                        ix_agent_tool_executions_patient_id_hash;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'agent_tool_executions_conversation_id_not_null'
                      AND conrelid =
                          'agent_tool_executions'::regclass
                ) AND NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'agent_tool_executions_patient_id_hash_not_null'
                      AND conrelid =
                          'agent_tool_executions'::regclass
                ) THEN
                    ALTER TABLE agent_tool_executions
                    RENAME CONSTRAINT
                        agent_tool_executions_conversation_id_not_null
                    TO
                        agent_tool_executions_patient_id_hash_not_null;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'agent_backend_write_requests_conversation_id_hash_not_null'
                      AND conrelid =
                          'agent_backend_write_requests'::regclass
                ) AND NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'agent_backend_write_requests_patient_id_hash_not_null'
                      AND conrelid =
                          'agent_backend_write_requests'::regclass
                ) THEN
                    ALTER TABLE agent_backend_write_requests
                    RENAME CONSTRAINT
                        agent_backend_write_requests_conversation_id_hash_not_null
                    TO
                        agent_backend_write_requests_patient_id_hash_not_null;
                END IF;
            END
            $$;
            """,
        ),
        (
            "20260729_0037_remove_fallback_reason",
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = current_schema()
                      AND table_name = 'agent_run_traces'
                      AND column_name = 'fallback_reason'
                ) THEN
                    UPDATE agent_run_traces
                    SET final_answer_source = fallback_reason
                    WHERE final_answer_source = ''
                      AND fallback_reason <> '';
                END IF;
            END
            $$;
            ALTER TABLE agent_run_traces
                DROP COLUMN IF EXISTS fallback_reason
            """,
        ),
        (
            "20260730_0038_agent_sync_attempt_fencing",
            """
            ALTER TABLE agent_sync_requests
                ADD COLUMN IF NOT EXISTS attempt_epoch
                INTEGER NOT NULL DEFAULT 0;
            ALTER TABLE agent_patient_locks
                ADD COLUMN IF NOT EXISTS attempt_epoch
                INTEGER NOT NULL DEFAULT 0
            """,
        ),
        (
            "20260730_0039_agent_pro_ctcae_surveys",
            f"""
            CREATE TABLE IF NOT EXISTS agent_pro_ctcae_surveys (
                id {_id_column_type(engine)},
                public_id VARCHAR(80) NOT NULL UNIQUE,
                patient_id_hash VARCHAR(64) NOT NULL,
                origin_message_id VARCHAR(160) NOT NULL UNIQUE,
                expected_origin_message_id VARCHAR(160) NOT NULL,
                trace_id VARCHAR(160) NOT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'AWAITING_RESPONSE',
                question_count INTEGER NOT NULL,
                current_question_index INTEGER NOT NULL DEFAULT 0,
                payload_ciphertext TEXT NOT NULL,
                payload_hash VARCHAR(64) NOT NULL,
                encryption_key_id VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL DEFAULT 1,
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                completed_at {timestamp},
                resolved_at {timestamp},
                response_expires_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS
                uq_agent_pro_ctcae_surveys_active_patient
            ON agent_pro_ctcae_surveys (patient_id_hash)
            WHERE status IN (
                'AWAITING_RESPONSE',
                'COMPLETED',
                'APPROVAL_PENDING'
            );
            CREATE INDEX IF NOT EXISTS
                ix_agent_pro_ctcae_surveys_response_expires_at
            ON agent_pro_ctcae_surveys (response_expires_at);
            CREATE INDEX IF NOT EXISTS
                ix_agent_pro_ctcae_surveys_expires_at
            ON agent_pro_ctcae_surveys (expires_at);

            CREATE TABLE IF NOT EXISTS agent_pro_ctcae_responses (
                id {_id_column_type(engine)},
                survey_id INTEGER NOT NULL REFERENCES
                    agent_pro_ctcae_surveys (id) ON DELETE CASCADE,
                item_code VARCHAR(80) NOT NULL,
                response_index INTEGER NOT NULL,
                source_user_message_id VARCHAR(160) NOT NULL,
                answered_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_pro_ctcae_responses_survey_item
                    UNIQUE (survey_id, item_code),
                CONSTRAINT uq_agent_pro_ctcae_responses_source_message
                    UNIQUE (source_user_message_id)
            );
            CREATE INDEX IF NOT EXISTS
                ix_agent_pro_ctcae_responses_survey_id
            ON agent_pro_ctcae_responses (survey_id)
            """,
        ),
        (
            "20260730_0040_agent_owned_approval_keys",
            """
            UPDATE agent_pending_actions
            SET status = 'SUPERSEDED',
                resolved_at = COALESCE(resolved_at, CURRENT_TIMESTAMP),
                updated_at = CURRENT_TIMESTAMP
            WHERE status IN ('PENDING', 'APPROVED', 'SENDING');

            ALTER TABLE agent_pending_actions
                ADD COLUMN IF NOT EXISTS approval_key_hash
                    VARCHAR(64) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS argument_hash
                    VARCHAR(64) NOT NULL DEFAULT '';

            CREATE UNIQUE INDEX IF NOT EXISTS
                uq_agent_pending_actions_approval_key_hash
            ON agent_pending_actions (approval_key_hash)
            WHERE approval_key_hash <> '';

            DROP INDEX IF EXISTS
                uq_agent_pending_actions_active_patient;
            CREATE UNIQUE INDEX
                uq_agent_pending_actions_active_patient
            ON agent_pending_actions (patient_id_hash)
            WHERE status IN ('PENDING', 'APPROVED', 'SENDING')
            """,
        ),
        (
            "20260730_0041_agent_trace_decision_evidence",
            """
            ALTER TABLE agent_run_steps
                ADD COLUMN IF NOT EXISTS evidence_ciphertext
                    TEXT NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS evidence_hash
                    VARCHAR(64) NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS encryption_key_id
                    VARCHAR(120) NOT NULL DEFAULT '';

            CREATE INDEX IF NOT EXISTS
                ix_agent_run_steps_evidence_hash
            ON agent_run_steps (evidence_hash)
            WHERE evidence_hash <> ''
            """,
        ),
        (
            "20260730_0042_agent_pending_food_selections",
            f"""
            CREATE TABLE IF NOT EXISTS agent_pending_selections (
                id {_id_column_type(engine)},
                public_id VARCHAR(80) NOT NULL UNIQUE,
                patient_id_hash VARCHAR(64) NOT NULL,
                origin_message_id VARCHAR(160) NOT NULL UNIQUE,
                source_chat_request_id VARCHAR(160) NOT NULL,
                trace_id VARCHAR(160) NOT NULL,
                selection_type VARCHAR(60) NOT NULL,
                payload_ciphertext TEXT NOT NULL,
                payload_hash VARCHAR(64) NOT NULL,
                encryption_key_id VARCHAR(120) NOT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
                selected_value_hash VARCHAR(64) NOT NULL DEFAULT '',
                resolved_by_message_id VARCHAR(160) NOT NULL DEFAULT '',
                version INTEGER NOT NULL DEFAULT 1,
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                resolved_at {timestamp},
                selection_expires_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS
                uq_agent_pending_selections_active_patient
            ON agent_pending_selections (patient_id_hash)
            WHERE status IN ('PENDING', 'RESOLVED');
            CREATE INDEX IF NOT EXISTS
                ix_agent_pending_selections_origin_message_id
            ON agent_pending_selections (origin_message_id);
            CREATE INDEX IF NOT EXISTS
                ix_agent_pending_selections_source_request
            ON agent_pending_selections (source_chat_request_id);
            CREATE INDEX IF NOT EXISTS
                ix_agent_pending_selections_trace_id
            ON agent_pending_selections (trace_id);
            CREATE INDEX IF NOT EXISTS
                ix_agent_pending_selections_selection_expires_at
            ON agent_pending_selections (selection_expires_at);
            CREATE INDEX IF NOT EXISTS
                ix_agent_pending_selections_expires_at
            ON agent_pending_selections (expires_at)
            """,
        ),
        (
            "20260802_0043_mfds_adverse_reaction_reference",
            f"""
            CREATE TABLE IF NOT EXISTS mfds_import_runs (
                run_id BIGINT PRIMARY KEY,
                source_file TEXT NOT NULL,
                source_sha256 VARCHAR(64) NOT NULL,
                extractor_version VARCHAR(80) NOT NULL,
                started_at {timestamp} NOT NULL,
                completed_at {timestamp},
                status VARCHAR(32) NOT NULL,
                stats_json TEXT
            );

            CREATE TABLE IF NOT EXISTS mfds_drug_products (
                item_seq VARCHAR(40) PRIMARY KEY,
                item_name TEXT NOT NULL,
                item_eng_name TEXT,
                entp_name TEXT,
                entp_eng_name TEXT,
                item_permit_date VARCHAR(20),
                etc_otc_code VARCHAR(80),
                cancel_name VARCHAR(80),
                cancel_date VARCHAR(20),
                change_date VARCHAR(40),
                atc_code VARCHAR(80),
                main_item_ingr TEXT,
                main_ingr_eng TEXT,
                material_name TEXT,
                search_text TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS mfds_label_documents (
                document_id BIGINT PRIMARY KEY,
                document_hash VARCHAR(64) NOT NULL UNIQUE,
                document_type VARCHAR(40) NOT NULL,
                raw_xml_zlib BYTEA NOT NULL,
                raw_xml_length BIGINT NOT NULL,
                parse_status VARCHAR(40) NOT NULL,
                parse_error TEXT
            );

            CREATE TABLE IF NOT EXISTS mfds_product_label_documents (
                item_seq VARCHAR(40) NOT NULL REFERENCES
                    mfds_drug_products (item_seq) ON DELETE CASCADE,
                document_id BIGINT NOT NULL REFERENCES
                    mfds_label_documents (document_id) ON DELETE CASCADE,
                change_date VARCHAR(40),
                PRIMARY KEY (item_seq, document_id)
            );

            CREATE TABLE IF NOT EXISTS mfds_label_sections (
                section_id BIGINT PRIMARY KEY,
                section_type VARCHAR(80) NOT NULL,
                section_text TEXT NOT NULL,
                section_hash VARCHAR(64) NOT NULL UNIQUE
            );

            CREATE TABLE IF NOT EXISTS mfds_document_label_sections (
                document_id BIGINT NOT NULL REFERENCES
                    mfds_label_documents (document_id) ON DELETE CASCADE,
                section_id BIGINT NOT NULL REFERENCES
                    mfds_label_sections (section_id) ON DELETE CASCADE,
                heading TEXT NOT NULL,
                section_path TEXT NOT NULL,
                section_order INTEGER NOT NULL,
                PRIMARY KEY (document_id, section_id, section_order)
            );

            CREATE TABLE IF NOT EXISTS mfds_adverse_reactions (
                reaction_id BIGINT PRIMARY KEY,
                normalized_term TEXT NOT NULL UNIQUE
            );

            CREATE TABLE IF NOT EXISTS mfds_section_adverse_reactions (
                mention_id BIGINT PRIMARY KEY,
                section_id BIGINT NOT NULL REFERENCES
                    mfds_label_sections (section_id) ON DELETE CASCADE,
                reaction_normalized TEXT NOT NULL,
                reaction_raw TEXT NOT NULL,
                organ_system_text TEXT,
                frequency_text TEXT,
                population_text TEXT,
                condition_text TEXT,
                assertion VARCHAR(40) NOT NULL,
                evidence_start INTEGER NOT NULL,
                evidence_end INTEGER NOT NULL,
                reaction_start INTEGER NOT NULL,
                reaction_end INTEGER NOT NULL,
                extraction_method VARCHAR(80) NOT NULL,
                extractor_version VARCHAR(80) NOT NULL,
                confidence DOUBLE PRECISION NOT NULL,
                review_status VARCHAR(80) NOT NULL
            );

            CREATE TABLE IF NOT EXISTS mfds_drug_aliases (
                alias_normalized VARCHAR(255) NOT NULL,
                item_seq VARCHAR(40) NOT NULL REFERENCES
                    mfds_drug_products (item_seq) ON DELETE CASCADE,
                source VARCHAR(80) NOT NULL DEFAULT 'manual',
                PRIMARY KEY (alias_normalized, item_seq)
            );

            CREATE INDEX IF NOT EXISTS ix_mfds_drug_products_item_name
                ON mfds_drug_products (item_name);
            CREATE INDEX IF NOT EXISTS ix_mfds_drug_products_atc_code
                ON mfds_drug_products (atc_code);
            CREATE INDEX IF NOT EXISTS ix_mfds_drug_products_cancel_name
                ON mfds_drug_products (cancel_name);
            CREATE INDEX IF NOT EXISTS ix_mfds_product_documents_document
                ON mfds_product_label_documents (document_id);
            CREATE INDEX IF NOT EXISTS ix_mfds_document_sections_document
                ON mfds_document_label_sections (document_id);
            CREATE INDEX IF NOT EXISTS ix_mfds_document_sections_section
                ON mfds_document_label_sections (section_id);
            CREATE INDEX IF NOT EXISTS ix_mfds_section_reactions_section
                ON mfds_section_adverse_reactions (section_id);
            CREATE UNIQUE INDEX IF NOT EXISTS uq_mfds_section_reaction_mention
                ON mfds_section_adverse_reactions (
                    section_id,
                    reaction_normalized,
                    assertion,
                    reaction_start,
                    reaction_end
                );
            CREATE INDEX IF NOT EXISTS ix_mfds_section_reactions_reaction
                ON mfds_section_adverse_reactions (reaction_normalized);
            CREATE INDEX IF NOT EXISTS ix_mfds_section_reactions_confidence
                ON mfds_section_adverse_reactions (confidence);
            CREATE INDEX IF NOT EXISTS ix_mfds_drug_aliases_alias
                ON mfds_drug_aliases (alias_normalized);

            CREATE OR REPLACE VIEW mfds_product_adverse_reaction_view AS
            SELECT
                p.item_seq,
                p.item_name,
                p.item_eng_name,
                p.entp_name,
                p.etc_otc_code,
                p.cancel_name,
                p.change_date,
                p.atc_code,
                p.main_item_ingr,
                p.main_ingr_eng,
                d.document_hash,
                s.section_id,
                ds.section_path,
                ds.heading AS section_heading,
                ds.section_order,
                r.reaction_id,
                r.normalized_term AS reaction_normalized,
                m.reaction_raw,
                m.organ_system_text,
                m.frequency_text,
                m.population_text,
                m.condition_text,
                m.assertion,
                substring(
                    s.section_text
                    FROM m.evidence_start + 1
                    FOR m.evidence_end - m.evidence_start
                ) AS evidence_text,
                m.evidence_start,
                m.evidence_end,
                m.reaction_start,
                m.reaction_end,
                m.extraction_method,
                m.extractor_version,
                m.confidence,
                m.review_status
            FROM mfds_drug_products p
            JOIN mfds_product_label_documents pd
              ON pd.item_seq = p.item_seq
            JOIN mfds_label_documents d
              ON d.document_id = pd.document_id
            JOIN mfds_document_label_sections ds
              ON ds.document_id = d.document_id
            JOIN mfds_label_sections s
              ON s.section_id = ds.section_id
            JOIN mfds_section_adverse_reactions m
              ON m.section_id = s.section_id
            JOIN mfds_adverse_reactions r
              ON r.normalized_term = m.reaction_normalized
            """,
        ),
        (
            "20260802_0044_cohere_vector_reference",
            f"""
            DO $migration$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_extension
                    WHERE extname = 'vector'
                ) THEN
                    RAISE EXCEPTION 'agent_vector_extension_required';
                END IF;
            END
            $migration$;

            CREATE TABLE IF NOT EXISTS mfds_adverse_reaction_embeddings (
                embedding_id {_id_column_type(engine)},
                reaction_id BIGINT NOT NULL REFERENCES
                    mfds_adverse_reactions (reaction_id) ON DELETE CASCADE,
                source_text TEXT NOT NULL,
                normalized_text TEXT NOT NULL,
                embedding public.vector(1024) NOT NULL,
                provider VARCHAR(80) NOT NULL,
                model_id VARCHAR(160) NOT NULL,
                model_region VARCHAR(80) NOT NULL,
                dimensions INTEGER NOT NULL,
                source_version VARCHAR(160) NOT NULL,
                source_sha256 VARCHAR(64) NOT NULL,
                embedded_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_mfds_reaction_embedding_dimensions
                    CHECK (dimensions = 1024),
                CONSTRAINT uq_mfds_reaction_embedding_version
                    UNIQUE (reaction_id, model_id, source_version)
            );

            CREATE TABLE IF NOT EXISTS agent_pro_ctcae_alias_embeddings (
                embedding_id {_id_column_type(engine)},
                symptom_term TEXT NOT NULL,
                korean_symptom_name TEXT NOT NULL,
                sheet_name VARCHAR(160) NOT NULL,
                alias_text TEXT NOT NULL,
                normalized_alias TEXT NOT NULL,
                embedding public.vector(1024) NOT NULL,
                provider VARCHAR(80) NOT NULL,
                model_id VARCHAR(160) NOT NULL,
                model_region VARCHAR(80) NOT NULL,
                dimensions INTEGER NOT NULL,
                source_version VARCHAR(160) NOT NULL,
                source_sha256 VARCHAR(64) NOT NULL,
                embedded_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_pro_ctcae_embedding_dimensions
                    CHECK (dimensions = 1024),
                CONSTRAINT uq_pro_ctcae_alias_embedding_version
                    UNIQUE (
                        symptom_term,
                        korean_symptom_name,
                        normalized_alias,
                        model_id,
                        source_version
                    )
            );

            CREATE INDEX IF NOT EXISTS
                ix_mfds_reaction_embeddings_normalized_text
            ON mfds_adverse_reaction_embeddings (normalized_text);
            CREATE INDEX IF NOT EXISTS
                ix_mfds_reaction_embeddings_model_version
            ON mfds_adverse_reaction_embeddings (model_id, source_version);
            CREATE INDEX IF NOT EXISTS
                ix_mfds_reaction_embeddings_cosine_hnsw
            ON mfds_adverse_reaction_embeddings
            USING hnsw (embedding public.vector_cosine_ops);

            CREATE INDEX IF NOT EXISTS
                ix_pro_ctcae_alias_embeddings_normalized_alias
            ON agent_pro_ctcae_alias_embeddings (normalized_alias);
            CREATE INDEX IF NOT EXISTS
                ix_pro_ctcae_alias_embeddings_model_version
            ON agent_pro_ctcae_alias_embeddings (model_id, source_version);
            CREATE INDEX IF NOT EXISTS
                ix_pro_ctcae_alias_embeddings_cosine_hnsw
            ON agent_pro_ctcae_alias_embeddings
            USING hnsw (embedding public.vector_cosine_ops);
            """,
        ),
        (
            "20260802_0045_pgvector_iterative_scan_requirement",
            """
            DO $migration$
            DECLARE
                installed_version TEXT;
                major_version INTEGER;
                minor_version INTEGER;
            BEGIN
                SELECT extversion
                INTO installed_version
                FROM pg_extension
                WHERE extname = 'vector';
                IF installed_version IS NULL THEN
                    RAISE EXCEPTION 'agent_vector_extension_required';
                END IF;
                major_version := split_part(installed_version, '.', 1)::INTEGER;
                minor_version := split_part(installed_version, '.', 2)::INTEGER;
                IF major_version = 0 AND minor_version < 8 THEN
                    RAISE EXCEPTION
                        'agent_pgvector_0_8_or_newer_required';
                END IF;
            END
            $migration$;
            """,
        ),
        (
            "20260802_0046_linked_clinical_symptom_concepts",
            f"""
            CREATE TABLE IF NOT EXISTS clinical_symptom_concepts (
                concept_id {_id_column_type(engine)},
                symptom_term TEXT NOT NULL,
                korean_symptom_name TEXT NOT NULL,
                sheet_name VARCHAR(160) NOT NULL,
                pro_ctcae_source_version VARCHAR(160) NOT NULL,
                created_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_clinical_symptom_concept_version
                    UNIQUE (
                        symptom_term,
                        korean_symptom_name,
                        sheet_name,
                        pro_ctcae_source_version
                    )
            );

            CREATE TABLE IF NOT EXISTS clinical_symptom_aliases (
                alias_id {_id_column_type(engine)},
                concept_id BIGINT NOT NULL REFERENCES
                    clinical_symptom_concepts (concept_id)
                    ON DELETE CASCADE,
                alias_text TEXT NOT NULL,
                normalized_alias TEXT NOT NULL,
                source_type VARCHAR(32) NOT NULL,
                source_version VARCHAR(160) NOT NULL,
                created_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_clinical_symptom_alias_source_type
                    CHECK (source_type IN ('PRO_CTCAE', 'MFDS', 'CURATED')),
                CONSTRAINT uq_clinical_symptom_alias_version
                    UNIQUE (
                        concept_id,
                        normalized_alias,
                        source_type,
                        source_version
                    )
            );

            CREATE TABLE IF NOT EXISTS mfds_reaction_concept_links (
                link_id {_id_column_type(engine)},
                reaction_id BIGINT NOT NULL REFERENCES
                    mfds_adverse_reactions (reaction_id)
                    ON DELETE CASCADE,
                concept_id BIGINT NOT NULL REFERENCES
                    clinical_symptom_concepts (concept_id)
                    ON DELETE CASCADE,
                link_type VARCHAR(32) NOT NULL,
                similarity DOUBLE PRECISION NOT NULL,
                verifier_model VARCHAR(160) NOT NULL DEFAULT '',
                verification_status VARCHAR(32) NOT NULL,
                mfds_source_version VARCHAR(160) NOT NULL,
                pro_ctcae_source_version VARCHAR(160) NOT NULL,
                created_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_mfds_reaction_concept_link_type
                    CHECK (
                        link_type IN (
                            'EXACT', 'ALIAS', 'VECTOR_LLM_VERIFIED'
                        )
                    ),
                CONSTRAINT ck_mfds_reaction_concept_status
                    CHECK (
                        verification_status IN (
                            'VERIFIED', 'REJECTED', 'REVIEW_REQUIRED'
                        )
                    ),
                CONSTRAINT ck_mfds_reaction_concept_similarity
                    CHECK (similarity >= 0.0 AND similarity <= 1.0),
                CONSTRAINT uq_mfds_reaction_concept_link_version
                    UNIQUE (
                        reaction_id,
                        concept_id,
                        mfds_source_version,
                        pro_ctcae_source_version
                    )
            );

            CREATE TABLE IF NOT EXISTS mfds_reaction_concept_decisions (
                decision_id {_id_column_type(engine)},
                normalized_text TEXT NOT NULL,
                status VARCHAR(32) NOT NULL,
                link_type VARCHAR(32) NOT NULL,
                best_similarity DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                verifier_model VARCHAR(160) NOT NULL DEFAULT '',
                candidate_concept_ids_json TEXT NOT NULL DEFAULT '[]',
                mfds_source_version VARCHAR(160) NOT NULL,
                pro_ctcae_source_version VARCHAR(160) NOT NULL,
                decided_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_mfds_reaction_concept_decision_status
                    CHECK (
                        status IN ('LINKED', 'UNMATCHED', 'REVIEW_REQUIRED')
                    ),
                CONSTRAINT ck_mfds_reaction_concept_decision_link_type
                    CHECK (
                        link_type IN (
                            'EXACT', 'ALIAS', 'VECTOR_LLM_VERIFIED'
                        )
                    ),
                CONSTRAINT ck_mfds_reaction_decision_similarity
                    CHECK (
                        best_similarity >= 0.0
                        AND best_similarity <= 1.0
                    ),
                CONSTRAINT uq_mfds_reaction_concept_decision_version
                    UNIQUE (
                        normalized_text,
                        mfds_source_version,
                        pro_ctcae_source_version
                    )
            );

            CREATE TABLE IF NOT EXISTS agent_symptom_resolution_states (
                trace_id VARCHAR(128) NOT NULL,
                symptom_sha256 VARCHAR(64) NOT NULL,
                concept_id BIGINT NOT NULL REFERENCES
                    clinical_symptom_concepts (concept_id)
                    ON DELETE CASCADE,
                match_type VARCHAR(32) NOT NULL,
                similarity DOUBLE PRECISION NOT NULL,
                pro_ctcae_source_version VARCHAR(160) NOT NULL,
                created_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                expires_at {timestamp} NOT NULL,
                PRIMARY KEY (trace_id, symptom_sha256),
                CONSTRAINT ck_agent_symptom_resolution_match_type
                    CHECK (
                        match_type IN ('EXACT', 'VECTOR_LLM_VERIFIED')
                    ),
                CONSTRAINT ck_agent_symptom_resolution_similarity
                    CHECK (similarity >= 0.0 AND similarity <= 1.0)
            );

            CREATE INDEX IF NOT EXISTS
                ix_clinical_symptom_aliases_lookup
            ON clinical_symptom_aliases (
                normalized_alias,
                source_version
            );
            CREATE INDEX IF NOT EXISTS
                ix_mfds_reaction_concept_links_concept
            ON mfds_reaction_concept_links (
                concept_id,
                verification_status,
                mfds_source_version,
                pro_ctcae_source_version
            );
            CREATE INDEX IF NOT EXISTS
                ix_mfds_reaction_concept_links_reaction
            ON mfds_reaction_concept_links (reaction_id);
            CREATE INDEX IF NOT EXISTS
                ix_mfds_reaction_concept_decisions_status
            ON mfds_reaction_concept_decisions (
                status,
                mfds_source_version,
                pro_ctcae_source_version
            );
            CREATE INDEX IF NOT EXISTS
                ix_agent_symptom_resolution_states_expires_at
            ON agent_symptom_resolution_states (expires_at);
            """,
        ),
        (
            "20260802_0047_symptom_concept_link_build_status",
            f"""
            CREATE TABLE IF NOT EXISTS
                clinical_symptom_concept_link_statuses (
                status_id {_id_column_type(engine)},
                concept_id BIGINT NOT NULL REFERENCES
                    clinical_symptom_concepts (concept_id)
                    ON DELETE CASCADE,
                mfds_source_version VARCHAR(160) NOT NULL,
                pro_ctcae_source_version VARCHAR(160) NOT NULL,
                status VARCHAR(32) NOT NULL,
                candidate_count INTEGER NOT NULL DEFAULT 0,
                linked_term_count INTEGER NOT NULL DEFAULT 0,
                verifier_model VARCHAR(160) NOT NULL DEFAULT '',
                processed_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_symptom_concept_link_build_status
                    CHECK (status IN ('COMPLETED', 'REVIEW_REQUIRED')),
                CONSTRAINT ck_symptom_concept_link_build_counts
                    CHECK (
                        candidate_count >= 0
                        AND linked_term_count >= 0
                    ),
                CONSTRAINT uq_symptom_concept_link_build_version
                    UNIQUE (
                        concept_id,
                        mfds_source_version,
                        pro_ctcae_source_version
                    )
            );

            CREATE INDEX IF NOT EXISTS
                ix_symptom_concept_link_statuses_version
            ON clinical_symptom_concept_link_statuses (
                status,
                mfds_source_version,
                pro_ctcae_source_version
            );
            """,
        ),
    ]


def required_migration_versions(engine: Engine) -> tuple[str, ...]:
    return tuple(version for version, _sql in _base_migrations(engine))


def ensure_agent_async_task_columns(engine: Engine) -> None:
    timestamp = _timestamp_type(engine)
    columns: dict[str, str] = {
        "max_attempts": "INTEGER NOT NULL DEFAULT 3",
        "deduplication_key": "VARCHAR(255)",
        "run_after": timestamp,
        "locked_by": "VARCHAR(160) NOT NULL DEFAULT ''",
        "locked_until": timestamp,
        "expires_at": timestamp,
    }
    with engine.begin() as connection:
        existing_columns = table_columns(connection, "agent_async_tasks")
        if not existing_columns:
            return
        for column_name, column_type in columns.items():
            if column_name in existing_columns:
                continue
            connection.execute(text(f"ALTER TABLE agent_async_tasks ADD COLUMN {column_name} {column_type}"))


def ensure_agent_worker_heartbeat_columns(engine: Engine) -> None:
    timestamp = _timestamp_type(engine)
    columns: dict[str, str] = {
        "stopped_at": timestamp,
        "current_task_request_id": "VARCHAR(160) NOT NULL DEFAULT ''",
        "current_task_type": "VARCHAR(60) NOT NULL DEFAULT ''",
        "processed_count": "INTEGER NOT NULL DEFAULT 0",
        "last_error": "TEXT NOT NULL DEFAULT ''",
    }
    with engine.begin() as connection:
        existing_columns = table_columns(connection, "agent_worker_heartbeats")
        if not existing_columns:
            return
        for column_name, column_type in columns.items():
            if column_name in existing_columns:
                continue
            connection.execute(text(f"ALTER TABLE agent_worker_heartbeats ADD COLUMN {column_name} {column_type}"))


def ensure_agent_feedback_columns(engine: Engine) -> None:
    timestamp = _timestamp_type(engine)
    columns: dict[str, str] = {
        "request_hash": "VARCHAR(64) NOT NULL DEFAULT ''",
        "response_status": "INTEGER NOT NULL DEFAULT 202",
        "response_json": "TEXT NOT NULL DEFAULT '{\"status\":\"accepted\"}'",
        "attempt_count": "INTEGER NOT NULL DEFAULT 0",
        "max_attempts": "INTEGER NOT NULL DEFAULT 3",
        "next_attempt_at": timestamp,
        "last_attempt_at": timestamp,
    }
    with engine.begin() as connection:
        existing_columns = table_columns(connection, "agent_feedback_links")
        if not existing_columns:
            return
        for column_name, column_type in columns.items():
            if column_name in existing_columns:
                continue
            connection.execute(
                text(
                    "ALTER TABLE agent_feedback_links "
                    f"ADD COLUMN {column_name} {column_type}"
                )
            )
        connection.execute(
            text(
                "UPDATE agent_feedback_links "
                "SET response_status = COALESCE(response_status, 202), "
                "response_json = COALESCE("
                "NULLIF(response_json, ''), '{\"status\":\"accepted\"}'"
                "), "
                "attempt_count = COALESCE(attempt_count, 0), "
                "max_attempts = COALESCE(max_attempts, 3), "
                "next_attempt_at = COALESCE("
                "next_attempt_at, created_at, CURRENT_TIMESTAMP"
                ") "
                "WHERE status IN ('ACCEPTED', 'RETRYABLE_FAILED')"
            )
        )
        connection.execute(
            text(
                "ALTER TABLE agent_feedback_links "
                "ALTER COLUMN feedback DROP NOT NULL"
            )
        )
        _ensure_agent_feedback_reaction_index(connection)
        connection.execute(
            text(
                "CREATE INDEX IF NOT EXISTS "
                "ix_agent_feedback_links_next_attempt_at "
                "ON agent_feedback_links (next_attempt_at)"
            )
        )


def _ensure_agent_feedback_reaction_index(connection) -> None:
    connection.execute(
        text(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS
                uq_agent_feedback_links_current_reaction
            ON agent_feedback_links (
                api_path,
                message_id,
                patient_id_hash
            )
            WHERE feedback IS NOT NULL
            """
        )
    )


def run_migrations(engine: Engine) -> list[str]:
    _require_postgresql(engine)
    applied = run_sql_migrations(engine, _base_migrations(engine))
    ensure_agent_async_task_columns(engine)
    ensure_agent_worker_heartbeat_columns(engine)
    ensure_agent_feedback_columns(engine)
    return applied
