from __future__ import annotations

from sqlalchemy import Engine, text

from shared.migrations import run_sql_migrations, table_columns


def _timestamp_type(engine: Engine) -> str:
    return "TIMESTAMP" if engine.dialect.name == "postgresql" else "DATETIME"


def _id_column_type(engine: Engine) -> str:
    if engine.dialect.name == "postgresql":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER NOT NULL PRIMARY KEY"


def _base_migrations(engine: Engine) -> list[tuple[str, str]]:
    timestamp = _timestamp_type(engine)
    return [
        (
            "20260615_0001_agent_async_tasks",
            f"""
            CREATE TABLE IF NOT EXISTS agent_async_tasks (
                id {_id_column_type(engine)},
                request_id VARCHAR(160) NOT NULL UNIQUE,
                task_type VARCHAR(60) NOT NULL,
                status VARCHAR(24) NOT NULL DEFAULT 'pending',
                payload_json TEXT NOT NULL,
                callback_context_json TEXT NOT NULL DEFAULT '{{}}',
                attempts INTEGER NOT NULL DEFAULT 0,
                max_attempts INTEGER NOT NULL DEFAULT 3,
                last_error TEXT NOT NULL DEFAULT '',
                accepted_at {timestamp},
                run_after {timestamp},
                started_at {timestamp},
                locked_by VARCHAR(160) NOT NULL DEFAULT '',
                locked_until {timestamp},
                completed_at {timestamp}
            )
            """,
        ),
        (
            "20260617_0002_agent_worker_heartbeats",
            f"""
            CREATE TABLE IF NOT EXISTS agent_worker_heartbeats (
                id {_id_column_type(engine)},
                worker_id VARCHAR(200) NOT NULL UNIQUE,
                status VARCHAR(24) NOT NULL DEFAULT 'running',
                started_at {timestamp},
                heartbeat_at {timestamp},
                stopped_at {timestamp},
                current_task_request_id VARCHAR(160) NOT NULL DEFAULT '',
                current_task_type VARCHAR(60) NOT NULL DEFAULT '',
                processed_count INTEGER NOT NULL DEFAULT 0,
                last_error TEXT NOT NULL DEFAULT ''
            )
            """,
        ),
        (
            "20260725_0003_agent_sync_requests",
            f"""
            CREATE TABLE IF NOT EXISTS agent_sync_requests (
                id {_id_column_type(engine)},
                api_path VARCHAR(160) NOT NULL,
                request_id VARCHAR(160) NOT NULL,
                request_hash VARCHAR(64) NOT NULL,
                conversation_id VARCHAR(160) NOT NULL,
                patient_id VARCHAR(160) NOT NULL,
                message_id VARCHAR(160) NOT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
                trace_id VARCHAR(160) NOT NULL DEFAULT '',
                response_status INTEGER,
                response_json TEXT NOT NULL DEFAULT '',
                last_error_code VARCHAR(80) NOT NULL DEFAULT '',
                created_at {timestamp},
                updated_at {timestamp},
                processing_started_at {timestamp},
                lease_expires_at {timestamp},
                completed_at {timestamp},
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_sync_requests_path_request UNIQUE (api_path, request_id)
            )
            """,
        ),
        (
            "20260725_0004_agent_conversation_locks",
            f"""
            CREATE TABLE IF NOT EXISTS agent_conversation_locks (
                id {_id_column_type(engine)},
                conversation_id VARCHAR(160) NOT NULL UNIQUE,
                request_id VARCHAR(160) NOT NULL,
                lease_expires_at {timestamp} NOT NULL,
                created_at {timestamp},
                updated_at {timestamp}
            )
            """,
        ),
        (
            "20260725_0005_agent_sync_request_lookup_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_sync_requests_conversation_status
            ON agent_sync_requests (conversation_id, status)
            """,
        ),
        (
            "20260725_0006_agent_sync_request_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_sync_requests_expires_at
            ON agent_sync_requests (expires_at)
            """,
        ),
        (
            "20260725_0007_agent_run_traces",
            f"""
            CREATE TABLE IF NOT EXISTS agent_run_traces (
                id {_id_column_type(engine)},
                trace_id VARCHAR(160) NOT NULL UNIQUE,
                request_id VARCHAR(160) NOT NULL,
                api_path VARCHAR(160) NOT NULL DEFAULT '',
                conversation_id VARCHAR(160) NOT NULL,
                message_id VARCHAR(160) NOT NULL DEFAULT '',
                patient_id_hash VARCHAR(64) NOT NULL DEFAULT '',
                environment VARCHAR(40) NOT NULL DEFAULT '',
                release_version VARCHAR(120) NOT NULL DEFAULT '',
                workflow_name VARCHAR(120) NOT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'PROCESSING',
                agent_name VARCHAR(120) NOT NULL DEFAULT '',
                decision_type VARCHAR(80) NOT NULL DEFAULT '',
                route VARCHAR(120) NOT NULL DEFAULT '',
                fallback_reason VARCHAR(160) NOT NULL DEFAULT '',
                prompt_version_id VARCHAR(120) NOT NULL DEFAULT '',
                provider VARCHAR(80) NOT NULL DEFAULT '',
                model_tier VARCHAR(40) NOT NULL DEFAULT '',
                model_id VARCHAR(255) NOT NULL DEFAULT '',
                input_hash VARCHAR(64) NOT NULL DEFAULT '',
                output_hash VARCHAR(64) NOT NULL DEFAULT '',
                input_tokens INTEGER NOT NULL DEFAULT 0,
                output_tokens INTEGER NOT NULL DEFAULT 0,
                estimated_cost_usd FLOAT NOT NULL DEFAULT 0,
                latency_ms INTEGER NOT NULL DEFAULT 0,
                tool_count INTEGER NOT NULL DEFAULT 0,
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                error_message TEXT NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{{}}',
                started_at {timestamp} NOT NULL,
                completed_at {timestamp},
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL
            )
            """,
        ),
        (
            "20260725_0008_agent_run_traces_request_status_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_run_traces_request_status
            ON agent_run_traces (request_id, status)
            """,
        ),
        (
            "20260725_0009_agent_run_traces_conversation_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_run_traces_conversation_created
            ON agent_run_traces (conversation_id, created_at)
            """,
        ),
        (
            "20260725_0010_agent_run_steps",
            f"""
            CREATE TABLE IF NOT EXISTS agent_run_steps (
                id {_id_column_type(engine)},
                trace_id VARCHAR(160) NOT NULL,
                sequence INTEGER NOT NULL,
                step_type VARCHAR(60) NOT NULL,
                step_name VARCHAR(120) NOT NULL DEFAULT '',
                status VARCHAR(32) NOT NULL DEFAULT '',
                tool_name VARCHAR(160) NOT NULL DEFAULT '',
                tool_version VARCHAR(80) NOT NULL DEFAULT '',
                argument_schema_version VARCHAR(80) NOT NULL DEFAULT '',
                argument_hash VARCHAR(64) NOT NULL DEFAULT '',
                side_effect_level VARCHAR(40) NOT NULL DEFAULT '',
                retry_count INTEGER NOT NULL DEFAULT 0,
                latency_ms INTEGER NOT NULL DEFAULT 0,
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{{}}',
                started_at {timestamp},
                completed_at {timestamp},
                created_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_run_steps_trace_sequence UNIQUE (trace_id, sequence),
                FOREIGN KEY(trace_id) REFERENCES agent_run_traces (trace_id) ON DELETE CASCADE
            )
            """,
        ),
        (
            "20260725_0011_agent_tool_executions",
            f"""
            CREATE TABLE IF NOT EXISTS agent_tool_executions (
                id {_id_column_type(engine)},
                trace_id VARCHAR(160) NOT NULL,
                request_id VARCHAR(160) NOT NULL,
                conversation_id VARCHAR(160) NOT NULL,
                tool_call_id VARCHAR(180) NOT NULL,
                tool_name VARCHAR(160) NOT NULL,
                tool_version VARCHAR(80) NOT NULL DEFAULT '',
                argument_schema_version VARCHAR(80) NOT NULL DEFAULT '',
                argument_hash VARCHAR(64) NOT NULL DEFAULT '',
                status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
                side_effect_level VARCHAR(40) NOT NULL DEFAULT '',
                attempt_count INTEGER NOT NULL DEFAULT 0,
                response_hash VARCHAR(64) NOT NULL DEFAULT '',
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                retryable BOOLEAN NOT NULL DEFAULT FALSE,
                metadata_json TEXT NOT NULL DEFAULT '{{}}',
                started_at {timestamp},
                completed_at {timestamp},
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_tool_executions_trace_call UNIQUE (trace_id, tool_call_id)
            )
            """,
        ),
        (
            "20260725_0012_agent_tool_executions_request_status_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_tool_executions_request_status
            ON agent_tool_executions (request_id, status)
            """,
        ),
        (
            "20260725_0013_agent_pending_actions",
            f"""
            CREATE TABLE IF NOT EXISTS agent_pending_actions (
                id {_id_column_type(engine)},
                public_id VARCHAR(80) NOT NULL UNIQUE,
                source_chat_request_id VARCHAR(160) NOT NULL,
                source_message_id VARCHAR(160) NOT NULL,
                trace_id VARCHAR(160) NOT NULL,
                conversation_id VARCHAR(160) NOT NULL,
                patient_id_hash VARCHAR(64) NOT NULL,
                action_type VARCHAR(60) NOT NULL,
                action_name VARCHAR(160) NOT NULL,
                tool_call_id VARCHAR(180) NOT NULL DEFAULT '',
                action_fingerprint VARCHAR(64) NOT NULL,
                target_resource_type VARCHAR(80) NOT NULL DEFAULT '',
                target_record_id VARCHAR(160) NOT NULL DEFAULT '',
                expected_version INTEGER,
                display_json TEXT NOT NULL DEFAULT '{{}}',
                payload_ciphertext TEXT NOT NULL DEFAULT '',
                payload_hash VARCHAR(64) NOT NULL DEFAULT '',
                encryption_key_id VARCHAR(120) NOT NULL DEFAULT '',
                status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
                confirmation_message_id VARCHAR(160) NOT NULL DEFAULT '',
                result_ciphertext TEXT NOT NULL DEFAULT '',
                result_hash VARCHAR(64) NOT NULL DEFAULT '',
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                execution_started_at {timestamp},
                resolved_at {timestamp},
                action_expires_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL
            )
            """,
        ),
        (
            "20260725_0014_agent_pending_actions_active_index",
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_pending_actions_active_conversation
            ON agent_pending_actions (conversation_id)
            WHERE status IN ('PENDING', 'EXECUTING')
            """,
        ),
        (
            "20260725_0015_agent_feedback_links",
            f"""
            CREATE TABLE IF NOT EXISTS agent_feedback_links (
                id {_id_column_type(engine)},
                api_path VARCHAR(160) NOT NULL,
                request_id VARCHAR(160) NOT NULL,
                request_hash VARCHAR(64) NOT NULL DEFAULT '',
                message_id VARCHAR(160) NOT NULL,
                conversation_id VARCHAR(160) NOT NULL,
                patient_id_hash VARCHAR(64) NOT NULL,
                trace_id VARCHAR(160) NOT NULL DEFAULT '',
                feedback BOOLEAN NOT NULL,
                feedback_text_ciphertext TEXT NOT NULL DEFAULT '',
                feedback_text_hash VARCHAR(64) NOT NULL DEFAULT '',
                encryption_key_id VARCHAR(120) NOT NULL DEFAULT '',
                status VARCHAR(32) NOT NULL DEFAULT 'ACCEPTED',
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                response_status INTEGER NOT NULL DEFAULT 202,
                response_json TEXT NOT NULL DEFAULT '{{"status":"accepted"}}',
                attempt_count INTEGER NOT NULL DEFAULT 0,
                max_attempts INTEGER NOT NULL DEFAULT 3,
                feedback_at {timestamp} NOT NULL,
                next_attempt_at {timestamp},
                last_attempt_at {timestamp},
                processed_at {timestamp},
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_feedback_links_path_request UNIQUE (api_path, request_id)
            )
            """,
        ),
        (
            "20260725_0016_agent_feedback_links_message_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_feedback_links_message_conversation
            ON agent_feedback_links (message_id, conversation_id)
            """,
        ),
        (
            "20260725_0017_agent_state_expiry_indexes",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_pending_actions_expires_at
            ON agent_pending_actions (expires_at)
            """,
        ),
        (
            "20260725_0018_agent_trace_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_run_traces_expires_at
            ON agent_run_traces (expires_at)
            """,
        ),
        (
            "20260725_0019_agent_tool_execution_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_tool_executions_expires_at
            ON agent_tool_executions (expires_at)
            """,
        ),
        (
            "20260725_0020_agent_feedback_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_feedback_links_expires_at
            ON agent_feedback_links (expires_at)
            """,
        ),
        (
            "20260725_0021_agent_backend_write_requests",
            f"""
            CREATE TABLE IF NOT EXISTS agent_backend_write_requests (
                id {_id_column_type(engine)},
                request_id VARCHAR(160) NOT NULL,
                source_chat_request_id VARCHAR(160) NOT NULL,
                conversation_id_hash VARCHAR(64) NOT NULL DEFAULT '',
                trusted_context_hash VARCHAR(64) NOT NULL,
                tool_call_id VARCHAR(180) NOT NULL,
                tool_name VARCHAR(160) NOT NULL,
                argument_hash VARCHAR(64) NOT NULL,
                expected_version INTEGER,
                status VARCHAR(32) NOT NULL DEFAULT 'PREPARED',
                attempt_count INTEGER NOT NULL DEFAULT 0,
                response_status INTEGER,
                response_json TEXT NOT NULL DEFAULT '',
                response_hash VARCHAR(64) NOT NULL DEFAULT '',
                error_code VARCHAR(80) NOT NULL DEFAULT '',
                created_at {timestamp} NOT NULL,
                updated_at {timestamp} NOT NULL,
                last_attempt_at {timestamp},
                completed_at {timestamp},
                expires_at {timestamp} NOT NULL,
                CONSTRAINT uq_agent_backend_write_requests_request UNIQUE (request_id),
                CONSTRAINT uq_agent_backend_write_requests_logical_call
                UNIQUE (
                    source_chat_request_id,
                    tool_name,
                    argument_hash,
                    trusted_context_hash
                )
            )
            """,
        ),
        (
            "20260725_0022_agent_backend_write_request_indexes",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_backend_write_requests_source_status
            ON agent_backend_write_requests (source_chat_request_id, status)
            """,
        ),
        (
            "20260725_0023_agent_backend_write_request_expiry_index",
            """
            CREATE INDEX IF NOT EXISTS ix_agent_backend_write_requests_expires_at
            ON agent_backend_write_requests (expires_at)
            """,
        ),
        (
            "20260725_0024_agent_backend_write_logical_call_index",
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_backend_write_requests_logical_call
            ON agent_backend_write_requests (
                source_chat_request_id,
                tool_name,
                argument_hash,
                trusted_context_hash
            )
            """,
        ),
        (
            "20260725_0025_agent_feedback_processing_policy",
            "SELECT 1",
        ),
    ]


def required_migration_versions(engine: Engine) -> tuple[str, ...]:
    return tuple(version for version, _sql in _base_migrations(engine))


def ensure_agent_async_task_columns(engine: Engine) -> None:
    timestamp = _timestamp_type(engine)
    columns: dict[str, str] = {
        "max_attempts": "INTEGER NOT NULL DEFAULT 3",
        "run_after": timestamp,
        "locked_by": "VARCHAR(160) NOT NULL DEFAULT ''",
        "locked_until": timestamp,
    }
    with engine.begin() as connection:
        existing_columns = table_columns(connection, "agent_async_tasks")
        if not existing_columns:
            return
        for column_name, column_type in columns.items():
            if column_name in existing_columns:
                continue
            connection.execute(text(f"ALTER TABLE agent_async_tasks ADD COLUMN {column_name} {column_type}"))


def ensure_agent_worker_heartbeat_columns(engine: Engine) -> None:
    timestamp = _timestamp_type(engine)
    columns: dict[str, str] = {
        "stopped_at": timestamp,
        "current_task_request_id": "VARCHAR(160) NOT NULL DEFAULT ''",
        "current_task_type": "VARCHAR(60) NOT NULL DEFAULT ''",
        "processed_count": "INTEGER NOT NULL DEFAULT 0",
        "last_error": "TEXT NOT NULL DEFAULT ''",
    }
    with engine.begin() as connection:
        existing_columns = table_columns(connection, "agent_worker_heartbeats")
        if not existing_columns:
            return
        for column_name, column_type in columns.items():
            if column_name in existing_columns:
                continue
            connection.execute(text(f"ALTER TABLE agent_worker_heartbeats ADD COLUMN {column_name} {column_type}"))


def ensure_agent_feedback_columns(engine: Engine) -> None:
    timestamp = _timestamp_type(engine)
    false_literal = "FALSE" if engine.dialect.name == "postgresql" else "0"
    columns: dict[str, str] = {
        "request_hash": "VARCHAR(64) NOT NULL DEFAULT ''",
        "response_status": "INTEGER NOT NULL DEFAULT 202",
        "response_json": "TEXT NOT NULL DEFAULT '{\"status\":\"accepted\"}'",
        "attempt_count": "INTEGER NOT NULL DEFAULT 0",
        "max_attempts": "INTEGER NOT NULL DEFAULT 3",
        "next_attempt_at": timestamp,
        "last_attempt_at": timestamp,
    }
    with engine.begin() as connection:
        existing_columns = table_columns(connection, "agent_feedback_links")
        if not existing_columns:
            return
        for column_name, column_type in columns.items():
            if column_name in existing_columns:
                continue
            connection.execute(
                text(
                    "ALTER TABLE agent_feedback_links "
                    f"ADD COLUMN {column_name} {column_type}"
                )
            )
        connection.execute(
            text(
                "UPDATE agent_feedback_links "
                f"SET feedback = COALESCE(feedback, {false_literal}), "
                "response_status = COALESCE(response_status, 202), "
                "response_json = COALESCE("
                "NULLIF(response_json, ''), '{\"status\":\"accepted\"}'"
                "), "
                "attempt_count = COALESCE(attempt_count, 0), "
                "max_attempts = COALESCE(max_attempts, 3), "
                "next_attempt_at = COALESCE("
                "next_attempt_at, created_at, CURRENT_TIMESTAMP"
                ") "
                "WHERE status IN ('ACCEPTED', 'RETRYABLE_FAILED')"
            )
        )
        if connection.dialect.name == "postgresql":
            connection.execute(
                text(
                    "ALTER TABLE agent_feedback_links "
                    "ALTER COLUMN feedback SET NOT NULL"
                )
            )
        connection.execute(
            text(
                "CREATE INDEX IF NOT EXISTS "
                "ix_agent_feedback_links_next_attempt_at "
                "ON agent_feedback_links (next_attempt_at)"
            )
        )


def run_migrations(engine: Engine) -> list[str]:
    applied = run_sql_migrations(engine, _base_migrations(engine))
    ensure_agent_async_task_columns(engine)
    ensure_agent_worker_heartbeat_columns(engine)
    ensure_agent_feedback_columns(engine)
    return applied
